-- Moved to ~/.config/nvim/after/plugin/transparency.lua - that's Neovim's
-- real "load last" location (after/ as a top-level runtimepath entry);
-- this directory (plugin/after/) never was. omarchy-theme-hotreload.lua
-- has been updated to re-source the new path after each theme reload.
--
-- This file is now an intentional no-op, kept only because this session
-- can't delete files in your chezmoi source - safe to `rm` it yourself:
--   rm "$(chezmoi source-path)/dot_config/nvim/plugin/after/transparency.lua"
-- (and `rmdir` the now-empty plugin/after/ directory alongside it)
